### ISSUE TITLE
Non-idiomatic usage in q7

### ISSUE THREAD

**Issue by jbrockmendel** [pola-rs/tpch#42]
In both the pandas and modin queries:

```
lineitem_filtered["l_year"] = lineitem_filtered["l_shipdate"].apply(
    lambda x: x.year
)
```

should be

```
lineitem_filtered["l_year"] = lineitem_filtered["l_shipdate"].dt.year
```

The polars_queries version uses the analogous idiom.  This made a pretty big difference locally.

**Comment by ritchie46** [comment]
Thanks, the implementations were forked from bodo.ai .I assumed they would be optimized.. Could you make a PR? I can do rerun.
