### ISSUE TITLE
Queries should be expressed in SQL as well to test polars SQL coverage of TPCH

### ISSUE THREAD

**Issue by osawyerr** [pola-rs/tpch#55]
Hi there,

Would be worth having the queries executed in SQL to test SQL coverage of TPCH by polars and also to make it easier to write the tests.

**Comment by ritchie46** [comment]
Yes! We should add that for polars as well.

**Comment by stinodego** [comment]
The purpose of this repo is to benchmark the engines. Polars SQL has the exact same underlying engine, so there's not much point in rewriting all the queries as SQL and running those.

I like having the queries in the native Polars API, so I'll close this as not planned for now. We can revisit if there is a concrete benefit of adding Polars SQL queries.

**Comment by osawyerr** [comment]
@stinodego the support of features in native Polars API vs Polars SQL is not 1 to 1. For example, its only recently that Polars SQL added support for `LIKE` queries https://github.com/pola-rs/polars/issues/12399 which was missing and is a fundamental part of SQL but has been supported in the native APi for a long time. As an example `LIKE` is used by various TPCH queries.

Expressing the TPCH benchmark as SQL as well ensures that Polars _SQL_ has full coverage of various SQL functionality used by analytical queries. SQL is more ubiquitous than the native Polars API.

**Comment by stinodego** [comment]
If you have a feature request for a specific SQL keyword, feel free to open an issue in the Polars main repo.
