### ISSUE TITLE
Usage of Python subprocess.run

### ISSUE THREAD

**Issue by ZuluPro** [pola-rs/tpch#64]
Each query is run through a Python subprocess (`subprocess.run`),
Don't you think it brings a lot of overhead as Python has to initiate its environment before running any logic ?

https://github.com/pola-rs/tpch/blob/e636fa943cf5d930d0f33a9983ff29966b1a9e9f/common_utils.py#L70

**Comment by stinodego** [comment]
I don't think the overhead is significant as long as we're running with `shell=False`, which we are.

But if you can showcase a significant overhead (by running with/without subprocess), feel free to post some timings and we can reconsider.
