### ISSUE TITLE
Are TPCH Benchmark results actual or not?

### ISSUE THREAD

**Issue by anmyachev** [pola-rs/tpch#94]
Hi! 

Polars' performance is very impressive. I would like to know if the results are up to date, because I did not find the library versions used. Do you have this information?

<img width="653" alt="image" src="https://github.com/pola-rs/tpch/assets/45976948/b34fdff8-e6ab-4610-82ae-523dbf0c36b9">

**Comment by stinodego** [comment]
I have actually just rerun the benchmarks for the latest versions of Polars, DuckDB, pandas, Dask, and PySpark. We will be publishing the results in the near future.

**Comment by YarShev** [comment]
@stinodego, which Modin engine do you use for benchmarking? Note that Modin on Ray is the most mature.

**Comment by stinodego** [comment]
We do not run Modin at the moment.

**Comment by YarShev** [comment]
As I see, Modin is on the picture. Is there a reason why you do not run Modin at the moment?

**Comment by stinodego** [comment]
Modin was a bit annoying to run because Ray does not yet support Python 3.12 (we were using the Ray backend). And it's the smallest of our competitors and not really comparable in terms of performance, so we dropped it for now. Can always re-add the queries later without much hassle.

**Comment by YarShev** [comment]
Modin is a library that is in the ecosystem of data processing as well as cudf, ibis and many more. It would be great to see the performance of those too.

**Comment by anmyachev** [comment]
> I have actually just rerun the benchmarks for the latest versions of Polars, DuckDB, pandas, Dask, and PySpark. We will be publishing the results in the near future.

@stinodego It's good to hear that, just tried to reproduce these results and on `n2-highmem-16` machine, with a factor of 10 including IO, I got the following results (for 8 queries):
* `polars==0.20.18`: 12.69 sec
* `pandas==2.2.1`: 190.15 sec

It looks like the pandas speed up was a little less than twice as fast. However, to be sure, I need to know which requests were taken into account in the total time shown on the graph. Could you also share this information?
